In [1]:
import tensorflow as tf

Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes
Each tensor has a data type and a shape
Data Types: type of information that is stored in the tensor (float32, int32, string, ...)
Shape: represents the dimension of data

In [2]:
# Creating Tensors -- Scalar (just one value) = tensor of rank 0
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.1415, tf.float64)

#### Rank

In [3]:
rank1_tensor = tf.Variable(['Test', 'Train', 'Data'], tf.string)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
rank2_tensor = tf.Variable([['hello', 'ok'], ['ok', 'bye']], tf.string)
rank3_tensor = tf.Variable([['hello', 'ok', 'new'], ['ok', 'bye', 'new2']], tf.string)

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### Shape
Tell us how many items we have in each dimension

In [5]:
rank2_tensor.shape

TensorShape([2, 2])

In [6]:
rank3_tensor.shape

TensorShape([2, 3])

In [7]:
rank1_tensor.shape

TensorShape([3])

### Changing Shape

In [8]:
tensor1 = tf.ones([1,2,3]) # Creamos un tensor de 1's con la forma [1,2,3], es decir, 1 array de 2 arrays internos con 3 elementos cada uno.
tensor1
# En total tenemos 6 elementos

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [9]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [10]:
# Cuando utilizamos -1, le estamos diciendo al tensor que infiera/calcule el tamaño que deberia tener con respecto al numero total de elementos
tensor3 = tf.reshape(tensor2, [3, -1])
tensor3
# En este caso, efectivamente infiere que si hay 3 arrays, necesita haber 2 elementos por cada array.

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [11]:
tf.rank(tensor3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Types of Tensors
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of Variable all of these tensors ara inmuttable

In [12]:
t = tf.ones([4,4,4,4])
t2 = tf.reshape(t, [256])
t3 = tf.reshape(t, [32, -1])
t3

<tf.Tensor: shape=(32, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [

In [13]:
tf.rank(t3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Evaluating Tensors
Get value of Tensor. We need to run a session to evaluate the tensor

In [ ]:
with tf.compat.v1.Session() as sess:
    t3.eval()